(define (problem Ext3_89)
	(:domain plannerExt3)
	(:objects
		C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 - contenido
		D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 - dia
	)

	(:init
		(predecesor C0 C2)
		(predecesor C1 C6)
		(predecesor C2 C6)
		(predecesor C3 C5)
		(predecesor C4 C5)

		(paralelo C6 C10)
		(paralelo C8 C4)
		(paralelo C10 C6)
		(paralelo C3 C2)
		(paralelo C6 C9)
		(paralelo C5 C9)

		(diaSiguiente D1 D0)
		(diaSiguiente D2 D1)
		(diaSiguiente D3 D2)
		(diaSiguiente D4 D3)
		(diaSiguiente D5 D4)
		(diaSiguiente D6 D5)
		(diaSiguiente D7 D6)
		(diaSiguiente D8 D7)
		(diaSiguiente D9 D8)
		(diaSiguiente D10 D9)

		(diaAnterior D0 D1)
		(diaAnterior D0 D2)
		(diaAnterior D0 D3)
		(diaAnterior D0 D4)
		(diaAnterior D0 D5)
		(diaAnterior D0 D6)
		(diaAnterior D0 D7)
		(diaAnterior D0 D8)
		(diaAnterior D0 D9)
		(diaAnterior D0 D10)
		(diaAnterior D1 D2)
		(diaAnterior D1 D3)
		(diaAnterior D1 D4)
		(diaAnterior D1 D5)
		(diaAnterior D1 D6)
		(diaAnterior D1 D7)
		(diaAnterior D1 D8)
		(diaAnterior D1 D9)
		(diaAnterior D1 D10)
		(diaAnterior D2 D3)
		(diaAnterior D2 D4)
		(diaAnterior D2 D5)
		(diaAnterior D2 D6)
		(diaAnterior D2 D7)
		(diaAnterior D2 D8)
		(diaAnterior D2 D9)
		(diaAnterior D2 D10)
		(diaAnterior D3 D4)
		(diaAnterior D3 D5)
		(diaAnterior D3 D6)
		(diaAnterior D3 D7)
		(diaAnterior D3 D8)
		(diaAnterior D3 D9)
		(diaAnterior D3 D10)
		(diaAnterior D4 D5)
		(diaAnterior D4 D6)
		(diaAnterior D4 D7)
		(diaAnterior D4 D8)
		(diaAnterior D4 D9)
		(diaAnterior D4 D10)
		(diaAnterior D5 D6)
		(diaAnterior D5 D7)
		(diaAnterior D5 D8)
		(diaAnterior D5 D9)
		(diaAnterior D5 D10)
		(diaAnterior D6 D7)
		(diaAnterior D6 D8)
		(diaAnterior D6 D9)
		(diaAnterior D6 D10)
		(diaAnterior D7 D8)
		(diaAnterior D7 D9)
		(diaAnterior D7 D10)
		(diaAnterior D8 D9)
		(diaAnterior D8 D10)
		(diaAnterior D9 D10)

		(= (numAsignados D0) 0)
		(= (numAsignados D1) 0)
		(= (numAsignados D2) 0)
		(= (numAsignados D3) 0)
		(= (numAsignados D4) 0)
		(= (numAsignados D5) 0)
		(= (numAsignados D6) 0)
		(= (numAsignados D7) 0)
		(= (numAsignados D8) 0)
		(= (numAsignados D9) 0)
		(= (numAsignados D10) 0)
	)

	(:goal (and 
		(ha_visto C2)
		(ha_visto C9)
		(ha_visto C3)
		(ha_visto C7)
		(ha_visto C5)
		(ha_visto C1)
		(ha_visto C0)
		(ha_visto C6)
		(ha_visto C4)
		(ha_visto C10)
		)
	)
)
