(define (problem juego-de-prueba-ext1-2)
	(:domain plannerExt1)
	(:objects
		C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 - contenido
		D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 - dia
	)

	(:init
		(predecesor C0 C5)
		(predecesor C1 C7)
		(predecesor C3 C7)
		(predecesor C6 C7)
		(predecesor C5 C8)
		(predecesor C7 C8)

		(dia-anterior D0 D1)
		(dia-anterior D0 D2)
		(dia-anterior D0 D3)
		(dia-anterior D0 D4)
		(dia-anterior D0 D5)
		(dia-anterior D0 D6)
		(dia-anterior D0 D7)
		(dia-anterior D0 D8)
		(dia-anterior D0 D9)
		(dia-anterior D1 D2)
		(dia-anterior D1 D3)
		(dia-anterior D1 D4)
		(dia-anterior D1 D5)
		(dia-anterior D1 D6)
		(dia-anterior D1 D7)
		(dia-anterior D1 D8)
		(dia-anterior D1 D9)
		(dia-anterior D2 D3)
		(dia-anterior D2 D4)
		(dia-anterior D2 D5)
		(dia-anterior D2 D6)
		(dia-anterior D2 D7)
		(dia-anterior D2 D8)
		(dia-anterior D2 D9)
		(dia-anterior D3 D4)
		(dia-anterior D3 D5)
		(dia-anterior D3 D6)
		(dia-anterior D3 D7)
		(dia-anterior D3 D8)
		(dia-anterior D3 D9)
		(dia-anterior D4 D5)
		(dia-anterior D4 D6)
		(dia-anterior D4 D7)
		(dia-anterior D4 D8)
		(dia-anterior D4 D9)
		(dia-anterior D5 D6)
		(dia-anterior D5 D7)
		(dia-anterior D5 D8)
		(dia-anterior D5 D9)
		(dia-anterior D6 D7)
		(dia-anterior D6 D8)
		(dia-anterior D6 D9)
		(dia-anterior D7 D8)
		(dia-anterior D7 D9)
		(dia-anterior D8 D9)
	)

	(:goal (and 
		(ha-visto C8)
		(ha-visto C9)
		(ha-visto C6)
		)
	)
)
