(define (problem juego-de-prueba-ext3-2)
	(:domain plannerExt3)
	(:objects
		C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 - contenido
		D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 - dia
	)

	(:init
		(predecesor C0 C6)
		(predecesor C2 C4)
		(predecesor C3 C9)

		(paralelo C4 C6)
		(paralelo C8 C4)
		(paralelo C2 C3)
		(paralelo C9 C8)
		(paralelo C8 C2)
		(paralelo C1 C2)

		(dia-siguiente D1 D0)
		(dia-siguiente D2 D1)
		(dia-siguiente D3 D2)
		(dia-siguiente D4 D3)
		(dia-siguiente D5 D4)
		(dia-siguiente D6 D5)
		(dia-siguiente D7 D6)
		(dia-siguiente D8 D7)
		(dia-siguiente D9 D8)

		(dia-anterior D0 D1)
		(dia-anterior D0 D2)
		(dia-anterior D0 D3)
		(dia-anterior D0 D4)
		(dia-anterior D0 D5)
		(dia-anterior D0 D6)
		(dia-anterior D0 D7)
		(dia-anterior D0 D8)
		(dia-anterior D0 D9)
		(dia-anterior D1 D2)
		(dia-anterior D1 D3)
		(dia-anterior D1 D4)
		(dia-anterior D1 D5)
		(dia-anterior D1 D6)
		(dia-anterior D1 D7)
		(dia-anterior D1 D8)
		(dia-anterior D1 D9)
		(dia-anterior D2 D3)
		(dia-anterior D2 D4)
		(dia-anterior D2 D5)
		(dia-anterior D2 D6)
		(dia-anterior D2 D7)
		(dia-anterior D2 D8)
		(dia-anterior D2 D9)
		(dia-anterior D3 D4)
		(dia-anterior D3 D5)
		(dia-anterior D3 D6)
		(dia-anterior D3 D7)
		(dia-anterior D3 D8)
		(dia-anterior D3 D9)
		(dia-anterior D4 D5)
		(dia-anterior D4 D6)
		(dia-anterior D4 D7)
		(dia-anterior D4 D8)
		(dia-anterior D4 D9)
		(dia-anterior D5 D6)
		(dia-anterior D5 D7)
		(dia-anterior D5 D8)
		(dia-anterior D5 D9)
		(dia-anterior D6 D7)
		(dia-anterior D6 D8)
		(dia-anterior D6 D9)
		(dia-anterior D7 D8)
		(dia-anterior D7 D9)
		(dia-anterior D8 D9)

		(= (num-asignados D0) 0)
		(= (num-asignados D1) 0)
		(= (num-asignados D2) 0)
		(= (num-asignados D3) 0)
		(= (num-asignados D4) 0)
		(= (num-asignados D5) 0)
		(= (num-asignados D6) 0)
		(= (num-asignados D7) 0)
		(= (num-asignados D8) 0)
		(= (num-asignados D9) 0)
	)

	(:goal (and 
		(ha-visto C2)
		(ha-visto C6)
		(ha-visto C9)
		(ha-visto C8)
		(ha-visto C1)
		)
	)
)
