(define (problem juego-de-prueba-ext2-2)
	(:domain plannerExt2)
	(:objects
		C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 - contenido
		D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 - dia
	)

	(:init
		(predecesor C0 C6)
		(predecesor C1 C9)
		(predecesor C2 C9)
		(predecesor C3 C8)

		(paralelo C2 C0)
		(paralelo C2 C4)
		(paralelo C3 C4)
		(paralelo C3 C4)

		(dia-siguiente D1 D0)
		(dia-siguiente D2 D1)
		(dia-siguiente D3 D2)
		(dia-siguiente D4 D3)
		(dia-siguiente D5 D4)
		(dia-siguiente D6 D5)
		(dia-siguiente D7 D6)
		(dia-siguiente D8 D7)
		(dia-siguiente D9 D8)

		(dia-anterior D0 D1)
		(dia-anterior D0 D2)
		(dia-anterior D0 D3)
		(dia-anterior D0 D4)
		(dia-anterior D0 D5)
		(dia-anterior D0 D6)
		(dia-anterior D0 D7)
		(dia-anterior D0 D8)
		(dia-anterior D0 D9)
		(dia-anterior D1 D2)
		(dia-anterior D1 D3)
		(dia-anterior D1 D4)
		(dia-anterior D1 D5)
		(dia-anterior D1 D6)
		(dia-anterior D1 D7)
		(dia-anterior D1 D8)
		(dia-anterior D1 D9)
		(dia-anterior D2 D3)
		(dia-anterior D2 D4)
		(dia-anterior D2 D5)
		(dia-anterior D2 D6)
		(dia-anterior D2 D7)
		(dia-anterior D2 D8)
		(dia-anterior D2 D9)
		(dia-anterior D3 D4)
		(dia-anterior D3 D5)
		(dia-anterior D3 D6)
		(dia-anterior D3 D7)
		(dia-anterior D3 D8)
		(dia-anterior D3 D9)
		(dia-anterior D4 D5)
		(dia-anterior D4 D6)
		(dia-anterior D4 D7)
		(dia-anterior D4 D8)
		(dia-anterior D4 D9)
		(dia-anterior D5 D6)
		(dia-anterior D5 D7)
		(dia-anterior D5 D8)
		(dia-anterior D5 D9)
		(dia-anterior D6 D7)
		(dia-anterior D6 D8)
		(dia-anterior D6 D9)
		(dia-anterior D7 D8)
		(dia-anterior D7 D9)
		(dia-anterior D8 D9)
	)

	(:goal (and 
		(ha-visto C0)
		(ha-visto C9)
		(ha-visto C2)
		(ha-visto C4)
		)
	)
)
