(define (problem Ext3)
    (:domain plannerExt3)
    (:objects
        c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13 c14 c15 - contenido
        d1 d2 d3 d4 d5 d6 d7 - dia
    )
    (:init
        (predecesor c1 c2)
        (predecesor c2 c3)
        (predecesor c3 c4)
        (predecesor c4 c5)
        (predecesor c5 c6)
        (predecesor c6 c7)

        (paralelo c1 c8)
        (paralelo c1 c9)
        (paralelo c1 c10)
        (paralelo c1 c11)

        (paralelo c7 c12)
        (paralelo c7 c13)
        (paralelo c7 c14)
        (paralelo c7 c15)

        (diaSiguiente d2 d1)
        (diaSiguiente d3 d2)
        (diaSiguiente d4 d3)
        (diaSiguiente d5 d4)
        (diaSiguiente d6 d5)
        (diaSiguiente d7 d6)

        (diaAnterior d1 d2)
        (diaAnterior d1 d3)
        (diaAnterior d1 d4)
        (diaAnterior d1 d5)
        (diaAnterior d1 d6)
        (diaAnterior d1 d7)
        (diaAnterior d2 d3)
        (diaAnterior d2 d4)
        (diaAnterior d2 d4)
        (diaAnterior d2 d5)
        (diaAnterior d2 d6)
        (diaAnterior d2 d7)
        (diaAnterior d3 d4)
        (diaAnterior d3 d5)
        (diaAnterior d3 d6)
        (diaAnterior d3 d7)
        (diaAnterior d4 d5)
        (diaAnterior d4 d6)
        (diaAnterior d4 d7)
        (diaAnterior d5 d6)
        (diaAnterior d5 d7)
        (diaAnterior d6 d7)

        (= (numAsignados d1) 0)
        (= (numAsignados d2) 0)
        (= (numAsignados d3) 0)
        (= (numAsignados d4) 0)
        (= (numAsignados d5) 0)
        (= (numAsignados d6) 0)
        (= (numAsignados d7) 0)
    )
    (:goal (ha_visto c7))
)